예외 처리



컴파일 에러 - 컴파일시 발생하는 오류

​			컴파일러가 소스코드(.java)에 대해 문법적으로 기본적인 검사를할 때 발생하는 오류.

​			이 에러가 없어야지 컴파일이 성공적으로 완료되고 클래스 파일(.class)이 생성된다.

​			

런타임 에러 - 실행 시(실행 중) 발생하는 에러

​			컴파일은 잘 되었어도 실행 중 에러에 의해 프로그램이 잘못될 수도 있다.

​			프로그램이 실행 중 동작을 멈추거나, 갑지기 프로그램이 종료되는 경우.

​			여기서 예외처리가 필요하다. 

​			

논리적 에러 - 실행은 되지만 의도와 다르게 동작하는 에러.



예외 클래스는 구조 ↓

![예외 클래스 구조](http://kinimage.naver.net/20150411_163/1428687016154oGdIz_GIF/4ppVR.gif)





여기서  Exception이 예외 처리 클래스이다.

이 클래스를 두가지로 나눌 수 있다.

그전에 Error 클래스 : 치명적 에러로 예외 처리 불가능한 에러, unchecked 에러에 포함됨.



1.Exception 클래스들 : RuntimeException을 제외한 나머지 Exception 클래스. 가운데있는 ...

​					주로 외부의 영향으로 발생할 수 있는 예외들.

​					ex) 존재하지 않는 파일이름 입력, 입력한 데이터형식이 잘못됨...

​					컴파일러에서 check를 해주기 때문에 'checked 언어'라고한다.

​					반드시 처리를 해줘야 한다.

​					try ~ catch나 throws 를 이용해 예외 처리를 한다.



2.RuntimeException 클래스들 : RuntimeException과 그 자손들. 세번째 있는 ...

​						주로 프로그래머의 실수에 의해서 발생되는 예외들. 

​						ex) 배열의 범위를 벗어남, 정수를 0으로 나눔, 형변환 잘못 ...

​						컴파일러에서 check를 안해주기 때문에 'unchecked 언어'라고 한다.

​						선택적 처리를 해줘도 된다. 

​						throws 이용 불가능하다. 코딩만 잘하면 쓸일이 거의 없다.





try ~ catch 

```
try {
    // 내용
} catch (Exception1 e1) {
    e.printStackTrace();
    System.out.println(e.getMessage());
} catch (Exception2 | Exception3 e2) {
	// or 역할, 부모 자식 클래스 동시 사용 못한다.
    if(e2 instanceof Exception2) {	
        // Exception2 예외일경우
    }
    else {
        // Exception3 예외일경우
    }
} finally {
    // 예외처리결과 상관없이 무조건 실행됨.
    // try or catch 안에 return 있어도 실행됨.
}
```





throw :  강제로 예외를 발생시킬 수 있다.

```
throw new Exception();
```

```
Exception e = new Exception(); 

throw e; 
```

​		

throw new Exception() 사용시 예외 처리 없으면 컴파일 에러. 

throw new RuntimeException() 사용시 예외 처리 없어도 컴파일 에러 안남.

​		-> checked 예외, unchecked 예외 차이.





throws : 메소드에서 예외 처리하는 방법이다. 

```
void method() throws Exception1, Exception2, ... ,ExceptionN {
	// 메소드 내용
}
```

이렇게 한다고 예외 처리가 되는게 아니라.

이 메소드를 호출한 상위 메소드에게 예외처리를 떠넘기는? 것이다.

```
public void method01(){
    try{
        method02();	// 반드시 try 안에서 호출해야한다.
    } catch(Exception e){
    	System.out.print("여기로 온다.");
	}

}

public void method02() throws Exception {
    throw new Exception("예외내용");
    // System.out.print("이코드는 닿지 않는다.컴파일 에러.");
}

```

이런식으로 method02의 예외를 호출한 method01에서 처리를 해주는 것이다. 

```
public class isNotJuminException extends RuntimeException{
	public isNotJuminException(){
		super("주민번호 자릿수가 틀립니다 (13자리로 입력해주세요)");
	}
	
	public void ment(){
		System.out.println("\n\n주민번호 자릿수가 틀려용");
		System.out.println("다시 입력하세용 OㅅO \n\n");
	}
}

if(jumin!=13){
	throw new isNotJuminException();
}
```

이런 식으로 사용도 가능하다. (사용자 정의 예외)



throws를 사용하는 이유 !!

- 한 예외상황에서 여러가지 처리방법이 필요할때. (대형프로젝트 파트별로 다른 처리 가능)
- 명시적으로 예외 처리를 위해
- 소스를 단순화하고 싶을 때. 
- 최상위 클래스에 Exception 만들어주고 캐치하여 예외발생시마다 처리해주는 경우도 있다.





try-with-resource : 입출력(I/O)과 관련된 클래스를 사용할 때 유용하다.

​	finally 안에 close를 넣으면 그와 관련에서 try ~catch 예외처리를 또해줘야한다.

​	그게 불편해서 나온 기능. JDK1.7버전부터 사용 가능.

```
try (FileInputStream fis = new FileInputStream("score.dat");

	DataInputStream dis = new DataInputStream(fis)) {

		while(true) {

		score = dis.readInt();	

		System.out.println(score);

		sum += score;

	}

} catch (EOFException e) {

	System.out.println("점수의 총합은 " + sum + "입니다.");

} catch (EOFException e) {

	ie.printStackTrace();

}
```

implements AutoCloseable 를  해줘야 사용 가능하다.

implements AutoCloseable 를 해주고 public void close() throws Exception 함수를 만들어 사용 가능

try(괄호안에) {}

}

괄호안에서 객체를 생성하면 try를 탈출할 때 자동적으로 이 객체의 close()가 호출된다.





억제된(suppressed) 예외

```
WorkException: WorkException발생!!!
	at CloseableResource.exceptionWork(TryWithResourceEx.java:30)
	at TryWithResourceEx.main(TryWithResourceEx.java:14)
	Suppressed: CloseException: CloseException발생!!!
		at CloseableResource.close(TryWithResourceEx.java:36)
		at TryWithResourceEx.main(TryWithResourceEx.java:15)
```

예외가 두개일 때 try-with-resource를 사용하면 이런식으로 콘솔창에 출력된다.

그냥 try-catch만 사용하면 마지막에 발생한 CloseException만 출력될 것이다.



예외 되던지기 (exception re-throwing)

하나의 예외에 대해서 호출한 메소드와 예외가 발생한 메소드 양쪽 모두에서 처리해줘야 할 작업이 있을 때 사용되는 방법이다.

```
class ExceptionEx17 {
	public static void main(String[] args) 
	{
		try  {
			method1();		
		} catch (Exception e)	{
			System.out.println("main메서드에서 예외가 처리되었습니다.");
		}
	}	// main메서드의 끝

	static void method1() throws Exception {
		try {
			throw new Exception();
		} catch (Exception e) {
			System.out.println("method1메서드에서 예외가 처리되었습니다.");
			throw e;			// 다시 예외를 발생시킨다.
		}
	}	// method1메서드의 끝

}
```

보통 리턴값이 있는 메소드에서 catch안에도 return 값을 넣어줘야하지만, 

되던지기 할경우에는 catch안에 리턴값이 없어도 된다.





연결된 예외 (chained Exception)

한 예외가 다른 예외를 발생 시킬 수 있다.

```
try {
	startInstall();		// 프로그램 설치에 필요한 준비를 한다.
	copyFiles();		// 파일들을 복사한다. 
} catch (SpaceException2 e)	{
	InstallException ie = new InstallException("설치중 예외발생");
	ie.initCause(e);
	throw ie;
} catch (MemoryException2 me) {
	InstallException ie = new InstallException("설치중 예외발생");
	ie.initCause(me);
	throw ie;
} finally {
	deleteTempFiles();	// 프로그램 설치에 사용된 임시파일들을 삭제한다.
}
```

사용하는 이유.

여러가지 예외를 하나의 큰 분류의 예외로 다루기 위해서.

catch 블럭을 작성할 때 조상과 자손을 같이 쓰면 예외의 종류를 알 수 없다.

그래서 예외를 포함시켜 상속관계가 아니어도 사용할 수 있게 한다.





```
static void startInstall() throws SpaceException2, MemoryException2 { 
	if(!enoughSpace()) { 		// 충분한 설치 공간이 없으면...
		throw new SpaceException2("설치할 공간이 부족합니다.");
	}

	if (!enoughMemory()) {		// 충분한 메모리가 없으면...
		throw new RuntimeException(new MemoryException("메모리가 부족합니다."));
	}
}
```

이런 식으로 checked예외를 unchecked예외로 바꿀 수 있게 해주기도 한다.





출처 : https://mdown.blog.me/221409777980

https://blog.naver.com/sooftware/221393913799

https://blog.naver.com/whwjddls859/221224237984

자바의정석 3판.